In [1]:
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  9 21:48:56 2023

@author: LENOVO
"""
#Study each example below. Guess the output before you run the codes...
######################################################################

'\nCreated on Thu Nov  9 21:48:56 2023\n\n@author: LENOVO\n'

In [2]:
######################################################################
for i in range(10):
    print(i)
    print (10*i)

0
0
1
10
2
20
3
30
4
40
5
50
6
60
7
70
8
80
9
90


In [3]:
######################################################################   
for j in range(10):
    print(j)

0
1
2
3
4
5
6
7
8
9


In [4]:
######################################################################
for i in range(0,10,2):
    print(i)
    print (10*i)

0
0
2
20
4
40
6
60
8
80


In [5]:
######################################################################
for i in range(10):
    if i%2==0:
        print("modulus is zero")
    else:
        print (i)

modulus is zero
1
modulus is zero
3
modulus is zero
5
modulus is zero
7
modulus is zero
9


In [6]:
######################################################################       
tr_letters = "şçöğüİı"
for letter in tr_letters:
    print(letter)

ş
ç
ö
ğ
ü
İ
ı


In [7]:
######################################################################
tr_letters = "şçöğüİı"
pswd = input("Your pwsd: ")
for char in pswd:
    if char in tr_letters:
        print("You can't use Turkish characters in your pswd")

Your pwsd: çiğdem
You can't use Turkish characters in your pswd
You can't use Turkish characters in your pswd


In [8]:
######################################################################
i=0;tr_letters = "şçöğüİı"
pswd = input("Your pwsd: ")
for char in pswd:
    if char in tr_letters:
        i=i+1
if i>0:
      print("You have entered {} Turkish characters.\nYou can't use Turkish characters in your pswd".format(i))


Your pwsd: çiğdem
You have entered 2 Turkish characters.
You can't use Turkish characters in your pswd


In [9]:
######################################################################
#See the effect when the indent of the second "if" is changed...
i=0;tr_letters = "şçöğüİı"
pswd = input("Your pwsd: ")
for char in pswd:
    if char in tr_letters:
        i=i+1
        if i>0:
              print("You have entered {} Turkish characters.\nYou can't use Turkish characters in your pswd".format(i))
#It becomes too bad now. Do you know why?
#(Because the second if runs inside the first if due to 
#the indented position of the second "if")

Your pwsd: çiğdem
You have entered 1 Turkish characters.
You can't use Turkish characters in your pswd
You have entered 2 Turkish characters.
You can't use Turkish characters in your pswd


In [10]:
######################################################################

#Evaluate the output of these commands in your mind first. Then run and see
#whether your evaluation is correct or not.
for i in range(10):
    if i%2==0:
        print(i,"-->square: ",i*i)
    elif i%3==0:
        print(i,"-->cube: ",pow(i,3))
    else:
        print (i)

0 -->square:  0
1
2 -->square:  4
3 -->cube:  27
4 -->square:  16
5
6 -->square:  36
7
8 -->square:  64
9 -->cube:  729


In [11]:
######################################################################
#Now we want to find the multipliers of prime numbers for a given number, say 20... 
#See the following (as a starting point, to see the effect):
for i in range(20):
    if i%2==0 and i%3!=0 and i%5!=0:
        print(i,"-->can be divided by 2")
    elif i%2!=0 and i%3==0 and i%5!=0:
        print(i,"-->can be divided by 3")
    elif i%2 !=0 and i%3 !=0 and i%5==0:
        print(i,"-->can be divided by 5")
    elif i%2==0 and i%3==0 and i%5!=0:
        print(i,"-->can be divided by 6: ") 
    else:
        print (i)    
#Better but not so good...

0
1
2 -->can be divided by 2
3 -->can be divided by 3
4 -->can be divided by 2
5 -->can be divided by 5
6 -->can be divided by 6: 
7
8 -->can be divided by 2
9 -->can be divided by 3
10
11
12 -->can be divided by 6: 
13
14 -->can be divided by 2
15
16 -->can be divided by 2
17
18 -->can be divided by 6: 
19


In [12]:
######################################################################
#Let's try the following:
number=int(0);
number=int(input("enter a number between 0 and 22: "));two=0;three=0;five=0;seven=0;
eleven=0;thirteen=0;seventeen=0;nineteen=0;
num=number;
while num%2==0: 
    num=num/2;two+=1
while num%3==0:
    num=num/3;three+=1;
while num%5==0:
    num=num/5;five+=1;
while num%7==0:
    num=num/7;seven+=1;
while num%11==0:
    num=num/11;eleven+=1;
while num%13==0:
    num=num/13;thirteen+=1;
while num%17==0:
    num=num/17;seventeen+=1;
while num%19==0:
    num=num/19;nineteen+=1;
print(number,"can be divided by: 2^{}*3^{}*5^{}*7^{}*11^{}*13^{}*17^{}*19^{}".format(two,three,five,seven,eleven,thirteen,seventeen,nineteen)) 
   

enter a number between 0 and 22: 21
21 can be divided by: 2^0*3^1*5^0*7^1*11^0*13^0*17^0*19^0


In [13]:
######################################################################
#Now let's do somethng better in the final print command:
number=int(0);
number=int(input("enter a number between 0 and 22: "));two=0;three=0;five=0;seven=0;
eleven=0;thirteen=0;seventeen=0;nineteen=0;
num=number;
while num%2==0: 
    num=num/2;two+=1
while num%3==0:
    num=num/3;three+=1;
while num%5==0:
    num=num/5;five+=1;
while num%7==0:
    num=num/7;seven+=1;
while num%11==0:
    num=num/11;eleven+=1;
while num%13==0:
    num=num/13;thirteen+=1;
while num%17==0:
    num=num/17;seventeen+=1;
while num%19==0:
    num=num/19;nineteen+=1;
str="";del str;
# Note: for numbers we use "variable=None"
# but for strings: "del string name"
str="1"
if two!=0:
    str=str+"*2^"+"%s"%two
if three!=0:
    str=str+"*3^"+"%s"%three
if five!=0:
    str=str+"*5^"+"%s"%five
if seven!=0:
    str=str+"*7^"+"%s"%seven
if eleven!=0:
    str=str+"*11^"+"%s"%eleven 
if thirteen!=0:
    str=str+"*13^"+"%s"%thirteen
if seventeen!=0:
    str=str+"*17^"+"%s"%seventeen
if nineteen!=0:
    str=str+"*19^"+"%s"%nineteen
print(number,"can be divided by: ", str)


enter a number between 0 and 22: 21
21 can be divided by:  1*3^1*7^1


In [15]:
######################################################################    
#Check whether a number is a prime number or not (Can you do it by using the codes above?)
# https://www.stechies.com/python-prime-number/

In [17]:
######################################################################
#Now we have some nupy examples...
# pip install numpy
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
type(arr)
len(arr)
arr.shape
print("Question: Find the positions of the elements that can be divided by 5")
#Let's do it...

Question: Find the positions of the elements that can be divided by 5


In [18]:
a=arr.shape
b=np.array(a)
type(a)
type(b)
print(a)
print(b)  #See the difference between a and b
b[0]
for i in range(b[0]):
    for j in range(b[1]):
        print(arr[i,j])

(4, 5)
[4 5]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [19]:
######################################################################

for i in range(b[0]):
    for j in range(b[1]):
        if arr[i,j]%5==0:
           print("index:",i,j,"-->element:",arr[i,j])

index: 0 4 -->element: 5
index: 1 4 -->element: 10
index: 2 4 -->element: 15
index: 3 4 -->element: 20


In [20]:
####################################################################   
#Let's now choose the diagonal elements and define it as an array
#First learn this:
data=[1,2,3,4,5,"Ali"]; xs = ["Mehmet"]
for item in data:
    xs.append(item)
print (xs) 

['Mehmet', 1, 2, 3, 4, 5, 'Ali']


In [21]:
# Also this...
prime_numbers = [2, 3, 5, 7, 9, 11]
# remove all elements
prime_numbers.clear()
# Updated prime_numbers List
print('List after clear():', prime_numbers)

List after clear(): []


In [22]:
#Also learn this...
print(b)
k=np.empty([2,2])
print(k)
# See: https://www.geeksforgeeks.org/numpy-empty-python/
#Now let's use it...
arr2=np.empty(shape=0)
print(arr2)

[4 5]
[[2.12199579e-314 4.67296746e-307]
 [7.13430793e-321 8.72140270e-312]]
[]


In [23]:
print(b)
for i in range(b[0]):
    for j in range(b[1]):
       if i==j:
          arr2=np.append(arr2,arr[i,j])
print("diagonal elements:\n",arr2)

[4 5]
diagonal elements:
 [ 1.  7. 13. 19.]


In [24]:
print(arr) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
# Also study this for sequences (not arrays!): https://kerteriz.net/python-diziler/
# Also useful: https://makitweb.com/sequences-and-lists-in-python/
# And: https://learnpython.com/blog/python-array-vs-list/
# https://www.kodeclik.com/python-array-vs-list/
# learn the difference between lists, sequences, and arrays...
# https://en.wikibooks.org/wiki/Python_Programming/Sequences#:~:text=Sequences%20allow%20you%20to%20store,are%20containers%20for%20sequential%20data.
# https://pythongeeks.org/python-sequences-types-examples/    
