In [1]:
import numpy as np

In [2]:
alist=[1,1.3,2,3,5,7,9.4,'Ali'] #define a python list
print(type(alist))
print(alist)

<class 'list'>
[1, 1.3, 2, 3, 5, 7, 9.4, 'Ali']


In [3]:
a1=np.array([1,2.3,4,5,8.9])

In [4]:
print(type(a1)) #define a numpy array

<class 'numpy.ndarray'>


In [5]:
print("Array is of type: ", type(a1))

Array is of type:  <class 'numpy.ndarray'>


In [6]:
print("Our np-rray is: ", a1)

Our np-rray is:  [1.  2.3 4.  5.  8.9]


In [19]:
a2=np.array([[1],[2],[3],[4],[5],[8.9]]) #define a numpy array in 1D (column matrix)

In [20]:
print(a2)

[[1. ]
 [2. ]
 [3. ]
 [4. ]
 [5. ]
 [8.9]]


In [21]:
a3=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #define a numpy array (a 4 by 3 matrix)

In [10]:
print(a3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
a4=np.eye(5, 5,  0, dtype = float)

In [28]:
print(a4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
a5=np.eye(5, 5,  -1, dtype = float)

In [30]:
print(a5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [31]:
a6=np.eye(5, 5,  -3, dtype = float)

In [16]:
print(a6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [32]:
a7=np.array([1,2,3, 0], dtype = 'float64') #another example for array construction in real elements

In [33]:
print(a7)

[1. 2. 3. 0.]


In [34]:
a8=np.array([1.2,2.,3.7, 0.5], dtype = 'int16') #another example for array construction in integer elements
print(a7)

[1. 2. 3. 0.]


In [35]:
a9=np.zeros(10);print(a9)  #construct a zero raw matrix (row involves 10 columns)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
a10=np.zeros([4,3]);print(a10)  #construct a zero 4 by 3 matrix

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
a11=np.full(8,7);print(a11) #construct a full raw matrix (row involves 8 columns with elements 7)

[7 7 7 7 7 7 7 7]


In [38]:
a12=np.full(8,7,dtype = 'float64');print(a12) #Now in real elements

[7. 7. 7. 7. 7. 7. 7. 7.]


In [39]:
a13=np.full([4,3],7);print(a13) #construct a full 4 by 3 matrix (with elements 7)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [40]:
#Now some matrix constructions with specific arrangements#
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a14=np.arange(0,10,2);print(a14)  #array-arrange starting from 0 up to 10 by 2 increments

[0 2 4 6 8]


In [42]:
a15=np.linspace(0,10,21);print(a15)  #linear space starting from 0 up to 10 with a total of 21 elements

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [43]:
a16=np.random.random((3,4));print(a16)  #costruct a 3 by 4 random matrix. 
#Note that default definition of random values are between 0 and 1###

[[0.18523859 0.45349927 0.08264277 0.48721704]
 [0.5117228  0.57597001 0.96327184 0.73978054]
 [0.12438975 0.96111713 0.11980197 0.10633012]]


In [44]:
a17=np.random.randint(10,20,15);print(a17) #Now define random integer of 15-element row matrix 
#with elements between 10 and 20-1=19. Note that last value=20 is not included

[13 11 12 13 17 19 11 13 16 12 16 13 19 15 18]


In [45]:
a18=np.random.randint(10,20,[5,6]);a18  # Now the same but in a 5 by 6 matrix
#let's see the shape and dimension of it

array([[14, 12, 11, 11, 18, 15],
       [19, 12, 19, 15, 15, 13],
       [10, 10, 10, 11, 14, 10],
       [16, 12, 14, 13, 17, 12],
       [16, 12, 16, 12, 14, 18]])

In [46]:
a18.shape     #it's a 5 by 6 matrix

(5, 6)

In [47]:
a18.ndim      # it is in 2D
#diagonal matrix again (a review with examples)

2

In [48]:
a19=np.eye(5,4);a19

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [49]:
a20=np.eye(5,4,-2);a20  #negative sign in -2 indicates row-wise shift (lower-diagonal)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [50]:
a21=np.eye(5,5);a21

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
a22=np.eye(5,5,1);a22 #positive sign in +1 indicates column-wise shift (upper-diagonal)
#See https://www.geeksforgeeks.org/numpy-eye-python/  for detailed explanation

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [52]:
#Now selections of parts of constructed matrices... (very important)...
a23=np.arange(1,30,2);a23 #construct our row array first

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [53]:
a24=a23[0:5:1];a24 #We select i=0 and j=5th element (indices start from 0 not from 1, 
# and the 5th element is not included !!!!)

array([1, 3, 5, 7, 9])

In [54]:
a25=a23[0:5:2];a25

array([1, 5, 9])

In [55]:
a26=a23[0::1];a26

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [56]:
a27=a23[:6:1];a27

array([ 1,  3,  5,  7,  9, 11])

In [57]:
a28=a23[::-1];a28

array([29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [58]:
a29=a23[:6:-1];a29   #i1 indicates reverse order from right to he left

array([29, 27, 25, 23, 21, 19, 17, 15])

In [59]:
a30=a23[:6:-2];a30

array([29, 25, 21, 17])

In [60]:
#Let's now do it for the column matrises
a31=np.array([np.arange(1,30,2)]).transpose();a31 #construct our column array first

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23],
       [25],
       [27],
       [29]])

In [61]:
a32=a31[0:5];a32 #select column elements between 0th and 4th elements(the 5th is not included)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
a33=a31[3:5];a33 #select column elements between 3rd and 4th elements(the 5th is not included)

In [ ]:
a34=a31[:4];a34 #select column elements between 0th and 3rd elements(the 4th is not included)

In [ ]:
a35=a31[3:];a35 #select elements from indice 3 to all

In [ ]:
a36=a31[3::-1];a36 #select elements from indice 3 to all but in the reverse order
#some examples in m by n matrices...

In [62]:
a37=np.random.randint(10,100,[7,7])

In [63]:
a37  #construction first

array([[63, 77, 91, 85, 80, 40, 94],
       [71, 39, 31, 32, 46, 57, 75],
       [80, 96, 27, 19, 18, 14, 57],
       [95, 25, 51, 35, 89, 23, 36],
       [90, 14, 31, 68, 44, 95, 35],
       [68, 49, 16, 24, 32, 52, 13],
       [38, 35, 70, 13, 76, 54, 76]])

In [64]:
a37[0,5]   #We select i=0 and j=5th element (indices start from 0 not from 1 !!!!)

40

In [ ]:
a37[3,4]   #We now select i=3 and j=4th element
"""our formula for row-wise selection: a23[start:stop:step]----
Defaıult value of start is 0 and stop value is not included"""

In [ ]:
a37[0:4:2]

In [ ]:
a37

In [ ]:
a37[:4:2]   #select the ows between i=0,2, and 4 (the 4th one is not included)
"""Formula: array[r-start:r-stop:r-increment,c-start:c-stop:c-increment], 
here r-:row, c-:column(stops are not included)"""

In [ ]:
a37[1:3:1]   #another example (first 2 rows are selected-stop index is not included!!!)

In [ ]:
a37[1:3,2:4] #select row 1,2 and column 2,3 (rw3 and colum 4 is not included)

In [ ]:
a37[2:6:3,4:7]    #select row 2,5 and column 4,5,6 (row 6 and column 7 is not included)

In [ ]:
a37

In [ ]:
a37[1:3:1,::-1]

In [ ]:
a37[::-1,]    #All rows are reversed

In [ ]:
a37[::-1]    #The same

In [ ]:
a37[::,::-1] #All columns are reversed

In [ ]:
a37[5:3:-1,::] # from row 5 to row 3 in the reverse direction (end point row 3 is not included''')

In [ ]:
a37[::,6:2:-2]   #from column 6 to 2 (end point 2 is not included!) with step 2

In [ ]:
#Now some matrix operations
a38=np.array([[1,2],[3,4]]);a39=np.array([[1,0],[2,5]])

In [ ]:
a40=np.eye(2);a40

In [ ]:
2*a40

In [ ]:
a41= np.dot(a38,a39);a41  #dot product formula: #dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

In [ ]:
a41=a38*a39;a41 #elementwise product

In [ ]:
a42=np.multiply(a38,a39);a42 #the same as before

In [ ]:
print ("the transpose of a38={0} is {1}".format(a38,a38.transpose()) )

In [ ]:
print ("the inverse of a38={0} is {1}".format(a38,np.linalg.inv(a38)) )

In [ ]:
a43=np.linalg.inv(a38);a43

In [ ]:
#proof that a43 is the inverse o a38 is as follows
np.dot(a38,a43)

In [ ]:
#now lets calculate the determinant
a38

In [ ]:
from numpy import linalg as adu; adu.det(a38)  

In [ ]:
np.linalg.det(a38)   #or like thisss
#now power of a matrix

In [ ]:
a38

In [ ]:
pow(a38,2)  #elementwise product(not matrix square)

In [ ]:
np.power(a38,2)

In [ ]:
#proof
np.dot(a38,a38)

In [ ]:
#A complicated example on shaping matrices
a43=np.array([[1,2,3,4,5,6,7,8,9],[0,1,2,0,3,0,0,1,0],[0,1,0,1,1,0,1,2,0],[1,0,0,0,0,1,1,0,0]]);a43

In [ ]:
a44=a43[::,0:4:2];a44

In [ ]:
a45=a43[0:5,:2].transpose();a45

In [ ]:
a46=np.dot(a44,a45);a46

In [ ]:
a47=np.dot(a43[::,0:4:2],a43[0:5,:2].transpose());a47 #a47 is the same as a46

In [ ]:
a48=a47.transpose();a48 #transpose of a47

In [ ]:
a49=np.linalg.inv(a46);a49 #find inverse of a46 or 47 gives no result here because it is a singular matrix (det=0)

In [ ]:
a50=a43[3:0:-1,0:3];a50

In [ ]:
a51=np.linalg.inv(a50);a51 #find inverse of a50

In [ ]:
#for proof:
np.dot(a51,a50)

In [ ]:
#NOW RESHAPE COMMAND----VERY IMPORTANT!!!
a52 = np.arange(6);a52

In [ ]:
a52.reshape((3, 2))

In [ ]:
np.reshape(a52, (2, 3))
 # C-like index ordering

In [ ]:
a53 = np.array([[1,2,3], [4,5,6]]);a53

In [ ]:
a54=np.reshape(a53, 6);a54

In [ ]:
a53.shape

In [ ]:
a54.shape

In [ ]:
a55= np.array([[2,3,4], [5,6,7]]);a55   

In [ ]:
a56=np.reshape(a55, (3, 2));a56
    #See the following wep page https://www.w3resource.com/numpy/manipulation/reshape.php
    #and https://geekflare.com/numpy-reshape-arrays-in-python/
    # and https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b
    #Use of -1 is as follows: 
"""Use -1 for at most one dimension in the new shape 
if you would like the dimension to be automatically inferred."""

In [ ]:
a57=np.arange(20) ;a57       

In [ ]:
# But let' suppose we wish to rehape it to 4 by 3 now
np.reshape(a57, (4,3))   # it gives error since we have totally 20 elements but 4 by 3 has 12 elements

In [ ]:
np.reshape(a57, (4,6))   # similarly we can't reshape a 1 by 20 matrix to a 4 by 6!!!!
#But we use -1 to let numpy determine the column number

In [ ]:
a58=np.reshape(a57, (4,-1));a58

In [ ]:
#it is just the same as follows:
a59=np.reshape(a57, (4,5));a59

In [ ]:
#Similarly:
a60=np.reshape(a57, (2,-1));a60

In [ ]:
a61=np.reshape(a57, (2,-2));a61

In [ ]:
a62=np.reshape(a57, (2,-3));a62

In [ ]:
a64=np.reshape(a57, (2,-7));a64  # all are the same

In [ ]:
a65=np.reshape(a57,[5,-1]);a65            

In [ ]:
a66=np.reshape(a57,[5,-9]);a66 

In [ ]:
a67=np.reshape(a57,[5,4]);a67  # all the last three ones are the same 
# note the folowing synta is gives the same result

In [ ]:
a68=a57.reshape(5,4);a68

In [ ]:
a69=a57.reshape(5,-1);a69
#How to create a column matrix by using reshaoe

In [ ]:
a70=np.arange(10).reshape((10, 1));a70

In [ ]:
np.array([np.arange(1,10)]).transpose()

In [ ]:
np.array([np.arange(1,30,2)]).transpose()   #see a31 above

In [ ]:
#NOW VSTACK AND HSTACK
#See the following web page: https://www.geeksforgeeks.org/numpy-hstack-in-python/
# # Python program explaining
# hstack() AND vstack()function
#EXAMPLE1
import numpy as np
# input array
in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

In [ ]:
in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr_hor = np.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr_hor)

In [ ]:
# Stacking the two arrays verticaltally
out_arr_ver = np.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr_ver)
#EXAMPLE2
# Python program explaining
# hstack() and vstack) function

In [ ]:
import numpy as np

# input array
in_arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1)

In [ ]:
in_arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr_hor = np.hstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr_hor)

In [ ]:
# Stacking the two arrays vertically
out_arr_ver = np.vstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr_ver)